// Negros Island Region LGUs for dropdowns
export const NEGROS_LGUS = [
  // Negros Occidental
  { name: 'Bacolod City', province: 'Negros Occidental' },
  { name: 'Bago City', province: 'Negros Occidental' },
  { name: 'Cadiz City', province: 'Negros Occidental' },
  { name: 'Escalante City', province: 'Negros Occidental' },
  { name: 'Himamaylan City', province: 'Negros Occidental' },
  { name: 'Kabankalan City', province: 'Negros Occidental' },
  { name: 'La Carlota City', province: 'Negros Occidental' },
  { name: 'Sagay City', province: 'Negros Occidental' },
  { name: 'San Carlos City', province: 'Negros Occidental' },
  { name: 'Silay City', province: 'Negros Occidental' },
  { name: 'Sipalay City', province: 'Negros Occidental' },
  { name: 'Talisay City', province: 'Negros Occidental' },
  { name: 'Victorias City', province: 'Negros Occidental' },
  { name: 'Binalbagan', province: 'Negros Occidental' },
  { name: 'Calatrava', province: 'Negros Occidental' },
  { name: 'Candoni', province: 'Negros Occidental' },
  { name: 'Cauayan', province: 'Negros Occidental' },
  { name: 'Enrique B. Magalona', province: 'Negros Occidental' },
  { name: 'Hinigaran', province: 'Negros Occidental' },
  { name: 'Hinoba-an', province: 'Negros Occidental' },
  { name: 'Ilog', province: 'Negros Occidental' },
  { name: 'Isabela', province: 'Negros Occidental' },
  { name: 'La Castellana', province: 'Negros Occidental' },
  { name: 'Manapla', province: 'Negros Occidental' },
  { name: 'Moises Padilla', province: 'Negros Occidental' },
  { name: 'Murcia', province: 'Negros Occidental' },
  { name: 'Pontevedra', province: 'Negros Occidental' },
  { name: 'Pulupandan', province: 'Negros Occidental' },
  { name: 'Salvador Benedicto', province: 'Negros Occidental' },
  { name: 'San Enrique', province: 'Negros Occidental' },
  { name: 'Toboso', province: 'Negros Occidental' },
  { name: 'Valladolid', province: 'Negros Occidental' },

  // Negros Oriental
  { name: 'Bais City', province: 'Negros Oriental' },
  { name: 'Bayawan City', province: 'Negros Oriental' },
  { name: 'Canlaon City', province: 'Negros Oriental' },
  { name: 'Dumaguete City', province: 'Negros Oriental' },
  { name: 'Guihulngan City', province: 'Negros Oriental' },
  { name: 'Tanjay City', province: 'Negros Oriental' },
  { name: 'Amlan', province: 'Negros Oriental' },
  { name: 'Ayungon', province: 'Negros Oriental' },
  { name: 'Bacong', province: 'Negros Oriental' },
  { name: 'Basay', province: 'Negros Oriental' },
  { name: 'Bindoy', province: 'Negros Oriental' },
  { name: 'Dauin', province: 'Negros Oriental' },
  { name: 'Jimalalud', province: 'Negros Oriental' },
  { name: 'La Libertad', province: 'Negros Oriental' },
  { name: 'Mabinay', province: 'Negros Oriental' },
  { name: 'Manjuyod', province: 'Negros Oriental' },
  { name: 'Pamplona', province: 'Negros Oriental' },
  { name: 'San Jose', province: 'Negros Oriental' },
  { name: 'Santa Catalina', province: 'Negros Oriental' },
  { name: 'Siaton', province: 'Negros Oriental' },
  { name: 'Sibulan', province: 'Negros Oriental' },
  { name: 'Tayasan', province: 'Negros Oriental' },
  { name: 'Valencia', province: 'Negros Oriental' },
  { name: 'Vallehermoso', province: 'Negros Oriental' },
  { name: 'Zamboanguita', province: 'Negros Oriental' },

  // Siquijor
  { name: 'Enrique Villanueva', province: 'Siquijor' },
  { name: 'Larena', province: 'Siquijor' },
  { name: 'Lazi', province: 'Siquijor' },
  { name: 'Maria', province: 'Siquijor' },
  { name: 'San Juan', province: 'Siquijor' },
  { name: 'Siquijor', province: 'Siquijor' },
];
