# Generated by Django 4.2 on 2026-02-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoa_name', models.CharField(max_length=255, unique=True)),
                ('cert_of_inc_no', models.CharField(max_length=100, unique=True)),
                ('reg_type', models.CharField(max_length=100)),
                ('issuance_date', models.DateField()),
                ('classification', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('total_members', models.IntegerField()),
                ('date_of_election', models.DateField()),
                ('term_of_office', models.CharField(max_length=100)),
                ('latest_legal_order', models.TextField(blank=True, null=True)),
                ('order_date_issued', models.DateField(blank=True, null=True)),
                ('status_findings', models.TextField(blank=True, null=True)),
                ('compliance_reports', models.TextField(blank=True, null=True)),
                ('evaluator_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('no_legal_standing', 'No legal standing'), ('dissolved', 'Dissolved'), ('revoked', 'Revoked'), ('term_expired', 'Term expired'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('violation_section_64', models.BooleanField(default=False)),
                ('violation_section_101', models.BooleanField(default=False)),
                ('violation_section_62', models.BooleanField(default=False)),
                ('date_of_last_update', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='NOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('violation_section_64', models.BooleanField(default=False)),
                ('violation_section_101', models.BooleanField(default=False)),
                ('violation_section_62', models.BooleanField(default=False)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('evaluator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('hoa_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novs', to='hoa_registry.hoaprofile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('penalties', models.TextField()),
                ('date', models.DateField()),
                ('evaluator', models.CharField(max_length=255)),
                ('mr_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('hoa_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oias_records', to='hoa_registry.hoaprofile')),
                ('nov_control_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oias_records', to='hoa_registry.nov')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.CharField(choices=[('1', 'Censure'), ('2', 'Fine'), ('3', 'Suspension of Privileges'), ('4', 'Suspension of Board'), ('5', 'Removal of Officers'), ('6', 'Revocation')], max_length=2)),
                ('description', models.TextField()),
                ('date_imposed', models.DateField()),
                ('effective_date', models.DateField()),
                ('evaluator', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('hoa_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='hoa_registry.hoaprofile')),
                ('oias_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoa_registry.oias')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.CharField(max_length=100, unique=True)),
                ('submission_comment', models.TextField()),
                ('date', models.DateField()),
                ('evaluator', models.CharField(max_length=255)),
                ('mr_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('hoa_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='hoa_registry.hoaprofile')),
                ('nov_control_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='hoa_registry.nov')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('board_appointment', 'Interim Board Appointments'), ('orientation', 'HOA Orientations'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('hoa_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hoa_registry.hoaprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
