# Generated by Django 4.2 on 2026-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoa_registry', '0002_update_nov_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoaprofile',
            name='cert_of_inc_no',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='compliance_reports',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='evaluator_name',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='issuance_date',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='latest_legal_order',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='order_date_issued',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='reg_type',
        ),
        migrations.RemoveField(
            model_name='hoaprofile',
            name='status_findings',
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='cert_of_incorp_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CERTIFICATE OF INCORPORATION. NO'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='cert_reference_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CERTIFICATE/REFERENCE NO.'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='date_of_incorp',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF INCORPORATION (HLURB/DHSUD) (mm/dd/yy)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='date_of_issuance',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF ISSUANCE (mm/dd/yy)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='date_of_last_submission',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF LAST SUBMISSION (mm/dd/yy)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='docket_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DOCKET NO.'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='election_reports',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('X', 'X'), ('N/A', 'N/A')], max_length=3, null=True, verbose_name='ELECTION REPORTS (✓, X , N/A)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='EMAIL ADDRESS'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='female_bods',
            field=models.IntegerField(blank=True, null=True, verbose_name='FEMALE BODs'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='female_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='FEMALE MEMBERS'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='financial_records',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('X', 'X'), ('N/A', 'N/A')], max_length=3, null=True, verbose_name='FINANCIAL RECORDS (✓, X , N/A)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='gis',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('X', 'X')], max_length=2, null=True, verbose_name='GIS (✓ / X)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='male_bods',
            field=models.IntegerField(blank=True, null=True, verbose_name='MALE BODs'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='male_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='MALE MEMBERS'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NO'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='president_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NAME OF PRESIDENT'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='registration_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='REGISTRATION (SEC/HIGC/HLURB/DHSUD)'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='REMARKS'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='total_bods',
            field=models.IntegerField(blank=True, null=True, verbose_name='TOTAL BODs'),
        ),
        migrations.AddField(
            model_name='hoaprofile',
            name='updated_list_of_members',
            field=models.CharField(blank=True, choices=[('✓', '✓'), ('X', 'X')], max_length=2, null=True, verbose_name='UPDATED LIST OF MEMBERS (✓ / X)'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BARANGAY'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CITY/MUNICIPALITY'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='classification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CLASSIFICATION (REGULAR, NON-REGULAR, GOVT ASSISTED, NEIGHBORHOOD, FEDERATION, CONFEDERATION)'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='date_of_election',
            field=models.DateField(blank=True, null=True, verbose_name='DATE OF ELECTION'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='hoa_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='NAME OF HOMEOWNERS ASSOCIATION'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PROVINCES'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('No legal standing', 'No legal standing'), ('Dissolved', 'Dissolved'), ('Revoked', 'Revoked'), ('Term expired', 'Term expired'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='DHSUD STATUS'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='term_of_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TERM OF OFFICE'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='total_members',
            field=models.IntegerField(blank=True, null=True, verbose_name='TOTAL MEMBERS'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='violation_section_101',
            field=models.BooleanField(default=False, verbose_name='Section 101'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='violation_section_62',
            field=models.BooleanField(default=False, verbose_name='Section 62'),
        ),
        migrations.AlterField(
            model_name='hoaprofile',
            name='violation_section_64',
            field=models.BooleanField(default=False, verbose_name='Section 64'),
        ),
    ]
