# Generated by Django 4.2 on 2026-02-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoa_registry', '0003_remove_hoaprofile_cert_of_inc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='control_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Control #'),
        ),
        migrations.AlterField(
            model_name='nov',
            name='date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='nov',
            name='evaluator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evaluator'),
        ),
        migrations.AlterField(
            model_name='nov',
            name='violation_section_101',
            field=models.BooleanField(default=False, verbose_name='Section 101'),
        ),
        migrations.AlterField(
            model_name='nov',
            name='violation_section_62',
            field=models.BooleanField(default=False, verbose_name='Section 62'),
        ),
        migrations.AlterField(
            model_name='nov',
            name='violation_section_64',
            field=models.BooleanField(default=False, verbose_name='Section 64'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='control_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Control #'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='evaluator',
            field=models.CharField(max_length=255, verbose_name='Evaluator'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='mr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50, verbose_name='MR Status'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='nov_control_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oias_records', to='hoa_registry.nov', verbose_name='NOV Control #'),
        ),
        migrations.AlterField(
            model_name='oias',
            name='penalties',
            field=models.TextField(verbose_name='Penalties'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='control_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Control #'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='evaluator',
            field=models.CharField(max_length=255, verbose_name='Evaluator'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50, verbose_name='MR Status'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='nov_control_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='hoa_registry.nov', verbose_name='NOV Control #'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='submission_comment',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
