# Generated by Django 6.0.2 on 2026-02-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRLSOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_proj', models.CharField(max_length=255, verbose_name='Name of Project')),
                ('proj_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Type')),
                ('type_of_application', models.CharField(blank=True, choices=[('New Application', 'New Application'), ('Reactivated', 'Reactivated Application'), ('Replacement', 'Replacement')], max_length=50, null=True)),
                ('status_of_application', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Archived', 'Archived'), ('Ongoing', 'Ongoing'), ('Endorsed to HREDRB', 'Endorsed to HREDRB')], default='Ongoing', max_length=50)),
                ('main_or_compliance', models.CharField(blank=True, choices=[('Main', 'Main'), ('Compliance', 'Compliance')], max_length=20, null=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('cr_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='CR No.')),
                ('ls_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='LS No.')),
                ('prov', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('mun_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality/City')),
                ('street_brgy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street/Brgy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_or_amended_crls', models.ManyToManyField(blank=True, to='trackerApp.crlsoption', verbose_name='New or Amended CRLS')),
                ('proj_owner_dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackerApp.developer', verbose_name='Project Owner/Developer')),
            ],
        ),
    ]
