# Generated by Django 6.0.2 on 2026-02-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='proj_owner_dev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
