# Generated by Django 6.0.2 on 2026-02-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0002_alter_projectapplication_proj_owner_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectapplication',
            name='new_or_amended_crls',
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='crls_options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='CR/LS Options'),
        ),
        migrations.DeleteModel(
            name='CRLSOption',
        ),
    ]
